use super::*;
use insta::{assert_snapshot, with_settings};

/// `user`, and a `post` referencing it from another model directory.
fn write_models_across_directories() {
    write_model(Path::new("models/admin/user.json"), &sample_table("user"));

    let mut post = sample_table("post");
    post.columns.push(ColumnDef {
        name: "user_id".into(),
        r#type: ColumnType::Simple(SimpleColumnType::Integer),
        nullable: false,
        default: None,
        comment: None,
        primary_key: None,
        unique: None,
        index: None,
        foreign_key: None,
    });
    post.constraints.push(TableConstraint::ForeignKey {
        name: Some("fk_post__user_id".into()),
        columns: vec!["user_id".into()],
        ref_table: "user".into(),
        ref_columns: vec!["id".into()],
        on_delete: None,
        on_update: None,
        orphan_strategy: Default::default(),
    });
    write_model(Path::new("models/blog/post.json"), &post);
}

/// Model directories do not reach the output. A Go directory is one package,
/// so both tables land in the same file and the relation between them
/// resolves without an import.
#[rstest]
#[case::gorm(Orm::Gorm, "models.go")]
#[serial]
#[tokio::test]
async fn export_writes_nested_model_directories_into_one_file(
    #[case] orm: Orm,
    #[case] file: &str,
) {
    let tmp = tempdir().unwrap();
    let _guard = CwdGuard::new(&tmp.path().to_path_buf());
    write_config();
    write_models_across_directories();

    cmd_export(orm, None).await.unwrap();

    let root = PathBuf::from("src/models");
    assert_eq!(std_fs::read_dir(&root).unwrap().count(), 1);
    let written = std_fs::read_to_string(root.join(file)).unwrap();
    with_settings!({ snapshot_suffix => format!("{orm:?}") }, {
        assert_snapshot!(written);
    });
}

/// The export root doubles as a source directory — a Go package — and
/// nothing in it is swept: a re-export replaces the one file an earlier
/// export wrote and leaves the user's own files, nested ones included, alone.
#[rstest]
#[case::gorm(Orm::Gorm, "models.go", "repository.go", "cache/store.go")]
#[serial]
#[tokio::test]
async fn export_replaces_only_its_own_models_file(
    #[case] orm: Orm,
    #[case] file: &str,
    #[case] sibling: &str,
    #[case] nested: &str,
) {
    let tmp = tempdir().unwrap();
    let _guard = CwdGuard::new(&tmp.path().to_path_buf());
    write_config();
    write_model(Path::new("models/user.json"), &sample_table("user"));

    let root = PathBuf::from("src/models");
    cmd_export(orm, None).await.unwrap();
    let first = std_fs::read_to_string(root.join(file)).unwrap();

    std_fs::create_dir_all(root.join(nested).parent().unwrap()).unwrap();
    std_fs::write(root.join(sibling), "user code").unwrap();
    std_fs::write(root.join(nested), "user code").unwrap();
    write_model(Path::new("models/post.json"), &sample_table("post"));
    cmd_export(orm, None).await.unwrap();

    assert_ne!(std_fs::read_to_string(root.join(file)).unwrap(), first);
    assert_eq!(
        std_fs::read_to_string(root.join(sibling)).unwrap(),
        "user code"
    );
    assert_eq!(
        std_fs::read_to_string(root.join(nested)).unwrap(),
        "user code"
    );
}

/// `models.go` is a name the user may already own, so a file that does not
/// open with the generated marker is reported instead of overwritten.
#[rstest]
#[case::gorm(Orm::Gorm, "models.go", "package models\n")]
#[serial]
#[tokio::test]
async fn export_refuses_a_models_file_it_did_not_write(
    #[case] orm: Orm,
    #[case] file: &str,
    #[case] own: &str,
) {
    let tmp = tempdir().unwrap();
    let _guard = CwdGuard::new(&tmp.path().to_path_buf());
    write_config();
    write_model(Path::new("models/user.json"), &sample_table("user"));

    let out = PathBuf::from("src/models").join(file);
    std_fs::create_dir_all("src/models").unwrap();
    std_fs::write(&out, own).unwrap();

    let err = cmd_export(orm, None).await.unwrap_err();

    assert!(err.to_string().contains("was not generated by vespertide"));
    assert_eq!(std_fs::read_to_string(&out).unwrap(), own);
}
